name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Insstall pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build the app
        run: pnpm build

      - name: Deploy to cloud pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=racetimer
